export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const SAVE_SHIPPING_INFO = 'SAVE_SHIPPING_INFO';
export const INCREMENT_QTY = 'INCREMENT_QTY';
export const DECREMENT_QTY = 'DECREMENT_QTY';

// WishList
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
